TABLE USERS: id,
identification,
cin,
nom,
prenom,
dateNais,
lieuNais,
nomPere,
nomMere,
domicile,
numTel,
profession,
attribut,
statu,
numUrg,
email,
img,
fb,
mdp,
observation
/*****************/
JSON FILE { "identification": "LEFORT",
"cin": 201011028460,
"nom": "LEFORT",
"prenom": "Nuno",
"dateNais": "29/07/00",
"lieuNais": "Tamatave",
"nomPere": "Jose Emile",
"nomMere": "Nina Noeline",
"domicile": "Rova lot0206",
"numTel": "0380994042",
"profession": "ENI M1",
"attribut": 1,
"statu": 1,
"numUrg": "0349134397",
"email": "lefortnuno@gmail.com",
"fb": "Trofel",
"mdp": "nuno" }